[package]
name = "letz"
version = "0.1.0"
edition = "2024"

[[example]]
name = "negative_perkeo"

[dependencies]
indicatif = { version = "0.17.11", features = ["rayon"] }
rand = "0.9.1"
rayon = "1.10.0"
strum = { version = "0.27.1", features = ["derive"] }
strum_macros = "0.27.1"
